### ISSUE TITLE
FEAT - Some kind of completion alert or notification

### ISSUE THREAD

**Issue by Telepon** [Yoshi662/Media_Downloader#2]
When using the program without any kind of verbose/debugging, the only way of knowing when the downloading & conversion has ended is looking for the finished file in the download directory.

This is not intuitive, so I suggest some kind of alert or notification that the download/conversion has ended, and also the "download" button to be "locked" (grayed out) until the end of the process.
The icing of the cake would be adding some kind of progress bar, but that's for another ticket.
![Anotación 2019-10-21 215532](https://user-images.githubusercontent.com/56177081/67238711-e9949a00-f44d-11e9-9a4a-4eef41b4aebf.png)

**Comment by Yoshi662** [comment]
In the next version the program will notify a completed download.
About the disabled button. I changed the code a bit, hoping that will fix it.
