### ISSUE TITLE
Wrong behaviour when trying to create a preset with a name already in use

### ISSUE THREAD

**Issue by Telepon** [Yoshi662/Media_Downloader#3]
When trying to create a preset with an already used name, at first, the interaction does not indicate any error, it just opens again.
If you create a preset again, then it throws the error message.

![mediadown](https://user-images.githubusercontent.com/56177081/93756537-8b47dc80-fc05-11ea-80f1-7eefee726ed7.gif)

**The error message should appear the first time**

**Comment by Yoshi662** [comment]
Fixed on 966b4ce
