### ISSUE TITLE
Does not load preset settings correctly

### ISSUE THREAD

**Issue by Telepon** [Yoshi662/Media_Downloader#4]
When creating a preset with a the "audio" setting, if I "load" the preset, it doesn't apply the audio setting.
![giff 1](https://user-images.githubusercontent.com/56177081/93932815-0b169980-fd21-11ea-9302-e728f17d4f91.gif)

**The preset should save and apply the type of media**

**Comment by Telepon** [comment]
Bug found with a newly generated presets file.

**Comment by Yoshi662** [comment]
Fixed on 966b4ce
