### ISSUE TITLE
The version displayed in the "Acerca de" menu is incorrect

### ISSUE THREAD

**Issue by Telepon** [Yoshi662/Media_Downloader#5]
The MediaDownloader version displayed in the "Acerca de" menu is incorrect.
The version used is the 0.6.8b, but the window shows it is the 0.6.7b version.
![imagen](https://user-images.githubusercontent.com/56177081/94919822-5f561200-04b5-11eb-9aad-32aa6b6f2d41.png)

**Comment by Yoshi662** [comment]
I revised the case and I don't know how the old version got uploaded as the new. (or a In between version with the version number not updated)
I've updated the download in the[ lastest release ](https://github.com/Yoshi662/Media_Downloader/releases/tag/0.6.8b)and it is fixed now.
